# Generated by Django 2.2.10 on 2021-09-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answertracker",
            options={"verbose_name": "История ответов", "verbose_name_plural": "История ответов"},
        ),
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Опрос", "verbose_name_plural": "Опросы"},
        ),
        migrations.AlterField(
            model_name="answertracker",
            name="answer_text",
            field=models.TextField(blank=True, verbose_name="Текст ответа"),
        ),
        migrations.AlterField(
            model_name="answertracker",
            name="choice_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.Choice",
                verbose_name="Отвте",
            ),
        ),
        migrations.AlterField(
            model_name="answertracker",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
        migrations.AlterField(
            model_name="answertracker",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.Question", verbose_name="Вопрос"
            ),
        ),
        migrations.AlterField(
            model_name="answertracker",
            name="quiz_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polls.Quiz", verbose_name="Опрос"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=1000, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="choice",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.Question", verbose_name="Вопрос"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(max_length=1000, verbose_name="Вопрос"),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("Текст", "Текст"),
                    ("Одиночный выбор", "Одиночный выбор"),
                    ("Множественный выбор", "Множественный выбор"),
                ],
                default="Одиночный выбор",
                max_length=8,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="polls.Quiz", verbose_name="Опрос"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="end_date",
            field=models.DateField(verbose_name="Дата окончания"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
